name: 'xbank'
services:
  mailpit:
    container_name: xbank-mailpit
    image: axllent/mailpit:latest
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - xbank-network-internal
  rabbitmq:
    container_name: xbank-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # app port (AMQP)
      - "15672:15672" # UI web
    networks:
      - xbank-network-internal
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  database:
    container_name: xbank-db
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: no
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5441:5432"
    networks:
      - xbank-network-internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: 'xbank-api'
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - database
      - mailpit
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
    ports:
      - "8080:8080"
    networks:
      - shared-network
      - xbank-network-internal

networks:
  shared-network:
    external: true
  xbank-network-internal:
    driver: bridge
volumes:
  pgdata:
  rabbitmq_data:
